version: "3.8"

services:
  postgres:
    container_name: postgres-task
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=empresa_db
      - POSTGRES_USER=taciano
      - POSTGRES_PASSWORD=password
    restart: always
    ports:
      - "5400:5432"
    networks:
      - postgres-task-network
  
  pgadmin:
    container_name: pgadmin4-task
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-task-network

networks: 
  postgres-task-network:
    driver: bridge